package com.unicartagena.turnos.view;

import com.unicartagena.turnos.model.ModeloTurnos;
import com.unicartagena.turnos.model.entity.Turno;
import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.JPanel;
import javax.swing.BorderFactory;
import javax.swing.SwingConstants;
import java.awt.Color;
import java.awt.Font;
import java.awt.Cursor;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author Dev-Ops
 */
public class VistaFormularioTurnos extends javax.swing.JFrame {

    /**
     * Creates new form VistaFormularioTurnos
     */
    public VistaFormularioTurnos() {
        initComponents();
        personalizarComponentes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        txtDiaIngreso = new javax.swing.JTextField();
        txtPlacaVehiculo = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        VerHistorial = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Registro de Clientes");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setPreferredSize(new java.awt.Dimension(700, 380));

        txtNombre.setBackground(new java.awt.Color(204, 255, 255));
        txtNombre.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(0, 0, 0));
        txtNombre.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtNombre.setToolTipText("");
        txtNombre.setActionCommand("<Not Set>");
        txtNombre.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 3, 1, 3));
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        txtApellido.setBackground(new java.awt.Color(204, 255, 255));
        txtApellido.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        txtApellido.setForeground(new java.awt.Color(0, 0, 0));
        txtApellido.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtApellido.setToolTipText("");
        txtApellido.setActionCommand("<Not Set>");
        txtApellido.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 3, 1, 3));
        txtApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoActionPerformed(evt);
            }
        });

        txtTelefono.setBackground(new java.awt.Color(204, 255, 255));
        txtTelefono.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        txtTelefono.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtTelefono.setToolTipText("");
        txtTelefono.setActionCommand("<Not Set>");
        txtTelefono.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 3, 1, 3));

        txtCorreo.setBackground(new java.awt.Color(204, 255, 255));
        txtCorreo.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        txtCorreo.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtCorreo.setToolTipText("");
        txtCorreo.setActionCommand("<Not Set>");
        txtCorreo.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 3, 1, 3));
        txtCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoActionPerformed(evt);
            }
        });

        txtDiaIngreso.setBackground(new java.awt.Color(204, 255, 255));
        txtDiaIngreso.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        txtDiaIngreso.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtDiaIngreso.setToolTipText("");
        txtDiaIngreso.setActionCommand("<Not Set>");
        txtDiaIngreso.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 3, 1, 3));
        txtDiaIngreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiaIngresoActionPerformed(evt);
            }
        });

        txtPlacaVehiculo.setBackground(new java.awt.Color(204, 255, 255));
        txtPlacaVehiculo.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        txtPlacaVehiculo.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtPlacaVehiculo.setToolTipText("");
        txtPlacaVehiculo.setActionCommand("<Not Set>");
        txtPlacaVehiculo.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 3, 1, 3));
        txtPlacaVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPlacaVehiculoActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Agregar Turno");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        VerHistorial.setBackground(new java.awt.Color(255, 255, 255));
        VerHistorial.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        VerHistorial.setForeground(new java.awt.Color(0, 0, 0));
        VerHistorial.setText("Ver Historial");
        VerHistorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerHistorialActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(VerHistorial, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                .addGap(25, 25, 25))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VerHistorial, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(124, 124, 124))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtPlacaVehiculo, javax.swing.GroupLayout.DEFAULT_SIZE, 658, Short.MAX_VALUE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtApellido, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTelefono)
                    .addComponent(txtCorreo)
                    .addComponent(txtDiaIngreso))
                .addGap(19, 19, 19))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(txtDiaIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPlacaVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String nombre = txtNombre.getText().trim();
        String apellido = txtApellido.getText().trim();
        String telefono = txtTelefono.getText().trim();
        String correo = txtCorreo.getText().trim();
        String diaIngreso = txtDiaIngreso.getText().trim();
        String placaVehiculo = txtPlacaVehiculo.getText().trim();
        String horaActual = LocalTime.now().format(DateTimeFormatter.ofPattern("HH:mm"));
        String fechaHoraIngreso = diaIngreso + " " + horaActual;
        if (validarDatos(nombre, apellido, telefono, correo, diaIngreso, placaVehiculo)) {
            // Validar que la fecha de ingreso no sea mayor que el momento actual
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm");
            try {
                LocalDateTime fechaIngreso = LocalDateTime.parse(diaIngreso, formatter);
                LocalDateTime now = LocalDateTime.now();

                if (fechaIngreso.isAfter(now)) {
                    JOptionPane.showMessageDialog(this, "La fecha de ingreso no puede ser mayor que la fecha y hora actual.", "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Formato de fecha inválido. Use el formato: yyyy-MM-dd HH:mm.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            //autoIncrementamos el turno
            int nuevoNumeroTurno = ModeloTurnos.obtenerUltimoTurno() + 1;

            // Convertir la placa a mayúsculas sostenidas antes de guardarla
            placaVehiculo = placaVehiculo.toUpperCase();

            ModeloTurnos.agregarTurno(nuevoNumeroTurno, nombre, apellido, telefono, correo, diaIngreso, placaVehiculo);
            JOptionPane.showMessageDialog(this, "Turno agregado exitosamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            limpiarCampos();
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtPlacaVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPlacaVehiculoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPlacaVehiculoActionPerformed

    private void txtDiaIngresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiaIngresoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiaIngresoActionPerformed

    private void txtCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoActionPerformed

    private void txtApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void VerHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerHistorialActionPerformed
        // TODO add your handling code here:
        new VistaHistorialTurnos().setVisible(true); // Se abriría una vista de historial
        this.dispose();
        this.setBounds(50, 200, 150, 40); // Ajustar la posición y tamaño
        this.setFont(new java.awt.Font("Tahoma", java.awt.Font.BOLD, 12));
        this.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
// Desactivar el borde de enfoque
    }//GEN-LAST:event_VerHistorialActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaFormularioTurnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaFormularioTurnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaFormularioTurnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaFormularioTurnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaFormularioTurnos().setVisible(true);
            }
        });
    }

    /**
     * Función auxiliar para personalizar la vista.
     */
    private void personalizarComponentes() {
        this.setTitle("Registro de Clientes - Sistema de Turnos");
        this.setLocationRelativeTo(null); // Centrar ventana
        personalizarCamposTexto();
    }

    /**
     * Personaliza los campos de texto para una mejor apariencia.
     */
    private void personalizarCamposTexto() {
        txtNombre.setBorder(javax.swing.BorderFactory.createTitledBorder("Nombre Completo"));
        txtApellido.setBorder(javax.swing.BorderFactory.createTitledBorder("Apellido"));
        txtTelefono.setBorder(javax.swing.BorderFactory.createTitledBorder("Teléfono"));
        txtCorreo.setBorder(javax.swing.BorderFactory.createTitledBorder("Correo Electrónico"));
        txtDiaIngreso.setBorder(javax.swing.BorderFactory.createTitledBorder("Día de Ingreso (ej. 2024-11-22 00:00)"));
        txtPlacaVehiculo.setBorder(javax.swing.BorderFactory.createTitledBorder("Placa Vehicular (AAA-123)"));
    }

    /**
     * Valida los datos antes de registrar un turno.
     */
    private boolean validarDatos(String nombre, String apellido, String telefono, String correo, String diaIngreso, String placaVehiculo) {
        if (nombre.isEmpty() || apellido.isEmpty() || telefono.isEmpty() || correo.isEmpty() || diaIngreso.isEmpty() || placaVehiculo.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Todos los campos son obligatorios.", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        if (!correo.matches("^[A-Za-z0-9+_.-]+@(.+)$")) {
            JOptionPane.showMessageDialog(this, "Correo inválido.", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        if (!telefono.matches("\\d{7,10}")) {
            JOptionPane.showMessageDialog(this, "Teléfono inválido. Debe tener entre 7 y 10 dígitos.", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        if (!placaVehiculo.matches("(?i)[a-z]{3}-[a-z0-9]{3}")) {
            JOptionPane.showMessageDialog(this, "Placa inválida. Formato: ABC-123 o abc-h25.", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
    }

    /**
     * Limpia los campos después de registrar un turno.
     */
    private void limpiarCampos() {
        txtNombre.setText("");
        txtApellido.setText("");
        txtTelefono.setText("");
        txtCorreo.setText("");
        txtDiaIngreso.setText("");
        txtPlacaVehiculo.setText("");
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton VerHistorial;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDiaIngreso;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPlacaVehiculo;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
