/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.unicartagena.turnos;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jahm1
 */
public class VistaListaTurnos extends javax.swing.JFrame {

    /**
     * Creates new form VistaListaTurnos
     */
    public VistaListaTurnos() {
        initComponents();
        ModeloTurnos.agregarObservador(this);
        actualizarTabla();
        configurarTablaPersonalizada();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaTurnos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tablaTurnos.setAutoCreateRowSorter(true);
        tablaTurnos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Apellido", "Teléfono", "Correo", "Día de Ingreso", "Placa de Vehículo", "Tiempo Transcurrido"
            }
        ));
        tablaTurnos.setPreferredSize(new java.awt.Dimension(600, 90));
        jScrollPane1.setViewportView(tablaTurnos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 773, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public void actualizarTabla() {
        DefaultTableModel modelo = (DefaultTableModel) tablaTurnos.getModel();
        modelo.setRowCount(0); // Limpiar la tabla

        for (Turno turno : ModeloTurnos.obtenerTurnos()) {
            Object[] fila = {
                turno.getNombre(),
                turno.getApellido(),
                turno.getTelefono(),
                turno.getCorreo(),
                turno.getHoraEntrada(),
                turno.getPlacaVehiculo(),
                calcularTiempoTranscurrido(turno.getHoraEntrada()) // Implementa esta lógica según tu necesidad
            };
            modelo.addRow(fila);
        }
    }

    private String calcularTiempoTranscurrido(String horaEntrada) {
        // Implementa la lógica para calcular el tiempo transcurrido
        // Por ejemplo, usando LocalDateTime y Duration
        // Aquí se devuelve un valor estático como ejemplo
        return "1h 30m";
    }

    private void configurarTablaPersonalizada() {
        // Ajustar el ancho de las columnas
        tablaTurnos.getColumnModel().getColumn(0).setPreferredWidth(100); // Nombre
        tablaTurnos.getColumnModel().getColumn(1).setPreferredWidth(100); // Apellido
        tablaTurnos.getColumnModel().getColumn(2).setPreferredWidth(100); // Teléfono
        tablaTurnos.getColumnModel().getColumn(3).setPreferredWidth(150); // Correo
        tablaTurnos.getColumnModel().getColumn(4).setPreferredWidth(100); // Día de Ingreso
        tablaTurnos.getColumnModel().getColumn(5).setPreferredWidth(120); // Placa Vehículo
        tablaTurnos.getColumnModel().getColumn(6).setPreferredWidth(150); // Tiempo Transcurrido

        // Habilitar el ordenamiento
        tablaTurnos.setAutoCreateRowSorter(true);

    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaListaTurnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaListaTurnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaListaTurnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaListaTurnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaListaTurnos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaTurnos;
    // End of variables declaration//GEN-END:variables
}
